"""create tables

Revision ID: bd006a88ea8a
Revises: 
Create Date: 2026-08-13 22:42:55.789476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bd006a88ea8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('users_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('img_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('users_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_users_id'), 'users', ['users_id'], unique=False)
    op.create_table('chatrooms',
    sa.Column('chatrooms_id', sa.Uuid(), nullable=True),
    sa.Column('users_id', sa.Uuid(), nullable=True),
    sa.Column('room_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chatrooms_id')
    )
    op.create_index(op.f('ix_chatrooms_chatrooms_id'), 'chatrooms', ['chatrooms_id'], unique=False)
    op.create_index(op.f('ix_chatrooms_users_id'), 'chatrooms', ['users_id'], unique=False)
    op.create_table('chats',
    sa.Column('chats_id', sa.Uuid(), nullable=False),
    sa.Column('chatrooms_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatrooms_id'], ['chatrooms.chatrooms_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chats_id')
    )
    op.create_index(op.f('ix_chats_chatrooms_id'), 'chats', ['chatrooms_id'], unique=False)
    op.create_index(op.f('ix_chats_chats_id'), 'chats', ['chats_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_chats_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_chatrooms_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_chatrooms_users_id'), table_name='chatrooms')
    op.drop_index(op.f('ix_chatrooms_chatrooms_id'), table_name='chatrooms')
    op.drop_table('chatrooms')
    op.drop_index(op.f('ix_users_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
